// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"github.com/google/wire"
	"github.com/hector-leite/desafio-idealctvm/domain/service/favoriteassetservice"
	"github.com/hector-leite/desafio-idealctvm/domain/service/quoteservice"
	"github.com/hector-leite/desafio-idealctvm/domain/service/userservice"
	"github.com/hector-leite/desafio-idealctvm/infra/config"
	"github.com/hector-leite/desafio-idealctvm/integration/yahoofinance"
)

// Injectors from wire.go:

func injectApp() App {
	config := ProvideConfig()
	dbConfig := config.DB
	dataManager := ProvideDB(dbConfig)
	cacheConfig := config.Cache
	cacheManager := ProvideCacheManager(cacheConfig)
	httpClient := ProvideHTTPClient()
	userService := userservice.NewUserService(dataManager)
	yahooFinanceConfig := config.YahooFinance
	yahooFinance := yahoofinance.NewYahooFinanceIntegration(httpClient, yahooFinanceConfig)
	quoteService := quoteservice.NewQuoteService(dataManager, cacheManager, yahooFinance)
	favoriteAssetOrderHandler := ProvideFavoriteAssetHandler(dataManager, yahooFinance)
	favoriteAssetService := favoriteuserassetservice.NewFavoriteUserAssetService(favoriteAssetOrderHandler, dataManager, yahooFinance)
	appService := NewAppService(userService, quoteService, favoriteAssetService, favoriteAssetOrderHandler)
	appIntegration := NewAppIntegration(yahooFinance)
	app := App{
		Config:       config,
		DataManager:  dataManager,
		CacheManager: cacheManager,
		HTTPClient:   httpClient,
		services:     appService,
		integrations: appIntegration,
	}
	return app
}

// wire.go:

var AppSet = wire.NewSet(
	bindingSet,

	ProvideDB,
	ProvideCacheManager,
	ProvideConfig,
	ProvideHTTPClient,

	ProvideFavoriteAssetHandler,

	NewAppService,
	NewAppIntegration,
)

var bindingSet = wire.NewSet(
	configSet,
	serviceSet,
	integrationSet,
)

var configSet = wire.NewSet(wire.FieldsOf(new(*config.Config),
	"App",
	"Cache",
	"DB",
	"Server",
	"YahooFinance",
),
)

var serviceSet = wire.NewSet(userservice.NewUserService, quoteservice.NewQuoteService, favoriteuserassetservice.NewFavoriteUserAssetService)

var integrationSet = wire.NewSet(yahoofinance.NewYahooFinanceIntegration)
